apiVersion: apps/v1
kind: Deployment
metadata:
  name: disco
  labels:
    app: disco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: disco
  template:
    metadata:
      labels:
        app: disco
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: disco-persistent-storage
          emptyDir: {}
      initContainers:
        - name: collectstatic
          image: disco
          volumeMounts:
            - name: disco-persistent-storage
              mountPath: /pvc
          command:
            - python
            - manage.py
            - collectstatic
            - --no-input
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: disco.settings.k8s
          envFrom:
            - secretRef:
                name: disco-secrets
          resources:
            requests:
              memory: 400Mi
              cpu: 100m
            limits:
              memory: 400Mi
              cpu: 100m
        - name: migrate
          image: disco
          volumeMounts:
            - name: disco-persistent-storage
              mountPath: /pvc
          command:
            - python
            - manage.py
            - migrate
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: disco.settings.k8s
          envFrom:
            - secretRef:
                name: disco-secrets
          resources:
            requests:
              memory: 400Mi
              cpu: 100m
            limits:
              memory: 400Mi
              cpu: 100m
      containers:
        - name: disco
          image: disco
          volumeMounts:
            - name: disco-persistent-storage
              mountPath: /pvc
          command:
            - gunicorn
            - disco.wsgi:application
            - -b
            - 0.0.0.0:8000
            - --capture-output
            - --log-level
            - DEBUG
            - --workers
            - "1"
            - --threads
            - "3"
            - --timeout
            - "90"
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: disco.settings.k8s
          envFrom:
            - secretRef:
                name: disco-secrets
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: 400Mi
              cpu: 100m
            limits:
              memory: 500Mi
              cpu: 100m
        - name: disco-nginx
          image: nginx:alpine
          volumeMounts:
            - name: disco-persistent-storage
              mountPath: /usr/share/nginx/html
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 50Mi
              cpu: 50m
            limits:
              memory: 50Mi
              cpu: 50m
