apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: disco
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - disco.lb.djnd.si
      secretName: disco-tls
  rules:
    - host: disco.lb.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: disco
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: disco-nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://disco.lb.djnd.si"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - files.disco.lb.djnd.si
      secretName: disco-nginx-tls
  rules:
    - host: files.disco.lb.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: disco-nginx
                port:
                  number: 80
