apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: disco
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: disco
    newName: rg.fr-par.scw.cloud/djnd/disco
    newTag: 'e85112f246e26b42433744983588f6e8d8572a0b'
