apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: disco
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: disco
    newName: rg.fr-par.scw.cloud/djnd/disco
    newTag: '10ac71cc39d11b7f40eab90af36d1e9897d96b3b'
