# Generated by Django 4.1.9 on 2023-07-07 13:55

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0003_locationpage_newhomepage_newslettersignuppage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('short_description', models.TextField(blank=True)),
                ('social_media', wagtail.fields.StreamField([('instagram', wagtail.blocks.URLBlock()), ('mastodon', wagtail.blocks.URLBlock()), ('twitter', wagtail.blocks.URLBlock()), ('facebook', wagtail.blocks.URLBlock()), ('website', wagtail.blocks.URLBlock()), ('podcast', wagtail.blocks.URLBlock()), ('linkedin', wagtail.blocks.URLBlock()), ('youtube', wagtail.blocks.URLBlock())], blank=True, use_json_field=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammeDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('location', models.TextField()),
                ('available_for', models.TextField()),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('timeslots', wagtail.fields.StreamField([('timeslot', wagtail.blocks.StructBlock([('time', wagtail.blocks.CharBlock()), ('panels_list', wagtail.blocks.StreamBlock([('panel', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock()), ('speaker_page', wagtail.blocks.PageChooserBlock(page_type=['home.NewsPage'], required=False)), ('description', wagtail.blocks.TextBlock())]))], use_json_field=True))]))], use_json_field=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
        ),
    ]
