# Generated by Django 4.1.9 on 2023-07-14 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_registered_alter_programmeday_timeslots_individual_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationPage',
        ),
    ]
