# Generated by Django 4.1.9 on 2023-07-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_registrationpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_scholarship_option', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Scholarship settings',
            },
        ),
    ]
