# Generated by Django 4.1.9 on 2023-07-14 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_metasettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThankYouForRegistrationPage',
        ),
    ]
