# Generated by Django 4.1.9 on 2023-07-14 11:56

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_thankyouforregistrationpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newhomepage',
            name='exposed_speakers',
            field=wagtail.fields.StreamField([('speaker', wagtail.blocks.ChoiceBlock(choices=[]))], blank=True, null=True, use_json_field=True),
        ),
    ]
