# Generated by Django 4.1.9 on 2023-07-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_programmeday_timeslots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='individual_organisation',
            field=models.TextField(blank=True),
        ),
    ]
