# Generated by Django 4.1.9 on 2023-07-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_individual_individual_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered',
            name='registration_fee',
            field=models.IntegerField(blank=True, choices=[(50, '€50 plus VAT (€61 total)'), (25, '€25 plus VAT or €30,50 in total (for those unable to afford the standard fee)'), (75, '€75 plus VAT or €91,50 in total (for those who want to support participants with subsidised fee)')], null=True),
        ),
    ]
