# Generated by Django 4.1.9 on 2023-07-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_registered_registration_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
