# Generated by Django 4.1.9 on 2023-07-15 11:14

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_registered_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
