# Generated by Django 4.1.9 on 2023-07-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_individual_individual_organisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualbyorganisation',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
