# Generated by Django 4.1.9 on 2023-07-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_individual_has_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
