# Generated by Django 4.1.9 on 2023-07-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_registered_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered',
            name='email',
            field=models.EmailField(error_messages={'unique': 'You have already registered for the conference using this email address. Please use an alternative address.'}, max_length=254, unique=True),
        ),
    ]
