# Generated by Django 4.1.9 on 2023-07-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_programmeday_timeslots'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakersandprogrammepage',
            name='show_speakers',
            field=models.BooleanField(default=False),
        ),
    ]
