# Generated by Django 4.1.9 on 2023-07-20 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('home', '0024_speakersandprogrammepage_show_speakers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metasettings',
            options={'verbose_name': 'Global site settings'},
        ),
        migrations.AddField(
            model_name='metasettings',
            name='privacy_policy_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
