# Generated by Django 4.1.9 on 2023-07-24 16:30

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_metasettings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('affiliation', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('project', models.TextField()),
                ('project_relevancy', models.TextField()),
                ('travel_subsidy', models.BooleanField(default=False)),
            ],
        ),
    ]
