# Generated by Django 4.1.9 on 2023-07-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_newhomepage_speaker_application_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredspeaker',
            name='project_benefit',
            field=models.TextField(default='lorem ipsum'),
            preserve_default=False,
        ),
    ]
