# Generated by Django 4.1.9 on 2023-07-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_registeredspeaker_project_benefit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='is_participant',
        ),
    ]
