# Generated by Django 4.1.9 on 2023-10-04 13:13

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_remove_newspage_speaker_speaker_news_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newhomepage',
            name='organized_by_text',
            field=wagtail.fields.RichTextField(),
        ),
    ]
