# Generated by Django 4.1.9 on 2023-10-09 10:01

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_newhomepage_organized_by_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmeday',
            name='timeslots',
            field=wagtail.fields.StreamField([('timeslot', wagtail.blocks.StructBlock([('time', wagtail.blocks.CharBlock(required=False)), ('panels_list', wagtail.blocks.StreamBlock([('panel', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(required=False)), ('speakers', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('link', wagtail.blocks.PageChooserBlock(required=False)), ('organisation', wagtail.blocks.CharBlock(required=False)), ('title', wagtail.blocks.CharBlock(required=False)), ('description', wagtail.blocks.RichTextBlock(required=False))])))]))], use_json_field=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
