# Generated by Django 4.1.9 on 2023-10-20 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('home', '0034_programmeday_location_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RenameModel(
            old_name='SpeakersAndProgrammePage',
            new_name='SpeakersPage',
        ),
        migrations.CreateModel(
            name='ProgrammeDayPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('programme_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='home.programmeday')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
