# Generated by Django 4.1.9 on 2023-10-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_programmepage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newhomepage',
            name='stream_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
