# Generated by Django 4.1.9 on 2023-11-02 12:31

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_newspage_gallery_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
